/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Danilo Vitorino
 */
public class frmPrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipalVIEW
     */
    public frmPrincipalVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnCadastrar = new javax.swing.JMenu();
        btnCadastrarCliente = new javax.swing.JMenuItem();
        btnCadastrarLivro = new javax.swing.JMenuItem();
        btnDevolverLivro = new javax.swing.JMenu();
        btnPesquisar = new javax.swing.JMenu();
        btnPesquisarLivro = new javax.swing.JMenuItem();
        btnPesquisarEmprestimo = new javax.swing.JMenuItem();
        btnExcluirLivro = new javax.swing.JMenu();
        btnEmprestarLivro = new javax.swing.JMenu();
        btnActualizarLivro = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem-Vindo(a) a Biblioteca");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/GettyImages-577674005_492115_zfpgiw.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setMargin(new java.awt.Insets(60, 0, 60, 60));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(496, 60));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCadastrar.setMargin(new java.awt.Insets(10, 2, 10, 10));

        btnCadastrarCliente.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCadastrarCliente.setText("Cliente");
        btnCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });
        btnCadastrar.add(btnCadastrarCliente);

        btnCadastrarLivro.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCadastrarLivro.setText("Livro");
        btnCadastrarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLivroActionPerformed(evt);
            }
        });
        btnCadastrar.add(btnCadastrarLivro);

        jMenuBar1.add(btnCadastrar);

        btnDevolverLivro.setText("Devolver Livro");
        btnDevolverLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDevolverLivro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDevolverLivro.setMargin(new java.awt.Insets(10, 2, 10, 10));
        btnDevolverLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDevolverLivroMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnDevolverLivro);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPesquisar.setMargin(new java.awt.Insets(10, 2, 10, 10));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnPesquisarLivro.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnPesquisarLivro.setText("Livro");
        btnPesquisarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLivroActionPerformed(evt);
            }
        });
        btnPesquisar.add(btnPesquisarLivro);

        btnPesquisarEmprestimo.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnPesquisarEmprestimo.setText("Emprestimo");
        btnPesquisarEmprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarEmprestimoMouseClicked(evt);
            }
        });
        btnPesquisarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarEmprestimoActionPerformed(evt);
            }
        });
        btnPesquisar.add(btnPesquisarEmprestimo);

        jMenuBar1.add(btnPesquisar);

        btnExcluirLivro.setText("Excluir Livro");
        btnExcluirLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirLivro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnExcluirLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirLivroMouseClicked(evt);
            }
        });
        btnExcluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLivroActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnExcluirLivro);

        btnEmprestarLivro.setText("Emprestar Livro");
        btnEmprestarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmprestarLivro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEmprestarLivro.setMargin(new java.awt.Insets(10, 2, 10, 10));
        btnEmprestarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmprestarLivro(evt);
            }
        });
        btnEmprestarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestarLivroActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnEmprestarLivro);

        btnActualizarLivro.setText("Actualizar Livro");
        btnActualizarLivro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnActualizarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarLivroMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnActualizarLivro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprestarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestarLivroActionPerformed
        
    }//GEN-LAST:event_btnEmprestarLivroActionPerformed

    private void btnCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivroActionPerformed
        frmCadastrarLivro objcadastrarlivro = new frmCadastrarLivro();
        objcadastrarlivro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarLivroActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        frmCadastrarCliente objcadastrarCliente = new frmCadastrarCliente();
        objcadastrarCliente.setVisible(true);
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEmprestarLivro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmprestarLivro
        frmEmprestar objemprestar = new frmEmprestar();
        objemprestar.setVisible(true);
    }//GEN-LAST:event_btnEmprestarLivro

    private void btnPesquisarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarLivroActionPerformed
        frmPesquisarLivro objpesquisar = new frmPesquisarLivro();
        objpesquisar.setVisible(true);
    }//GEN-LAST:event_btnPesquisarLivroActionPerformed

    private void btnPesquisarEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarEmprestimoMouseClicked
        
    }//GEN-LAST:event_btnPesquisarEmprestimoMouseClicked

    private void btnPesquisarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarEmprestimoActionPerformed
        frmPesquisarEmprestimo objpesquisaremprestimo = new frmPesquisarEmprestimo();
        objpesquisaremprestimo.setVisible(true);
    }//GEN-LAST:event_btnPesquisarEmprestimoActionPerformed

    private void btnExcluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLivroActionPerformed
        
    }//GEN-LAST:event_btnExcluirLivroActionPerformed

    private void btnExcluirLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirLivroMouseClicked
        frmExcluirLivro objexcluirlivro = new frmExcluirLivro();
        objexcluirlivro.setVisible(true);
    }//GEN-LAST:event_btnExcluirLivroMouseClicked

    private void btnDevolverLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverLivroMouseClicked
        frmDevolverLivro objdevolverlivro = new frmDevolverLivro();
        objdevolverlivro.setVisible(true);
    }//GEN-LAST:event_btnDevolverLivroMouseClicked

    private void btnActualizarLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarLivroMouseClicked
        frmActualizarLivro objactualizarlivro = new frmActualizarLivro();
        objactualizarlivro.setVisible(true);
    }//GEN-LAST:event_btnActualizarLivroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnActualizarLivro;
    private javax.swing.JMenu btnCadastrar;
    private javax.swing.JMenuItem btnCadastrarCliente;
    private javax.swing.JMenuItem btnCadastrarLivro;
    private javax.swing.JMenu btnDevolverLivro;
    private javax.swing.JMenu btnEmprestarLivro;
    private javax.swing.JMenu btnExcluirLivro;
    private javax.swing.JMenu btnPesquisar;
    private javax.swing.JMenuItem btnPesquisarEmprestimo;
    private javax.swing.JMenuItem btnPesquisarLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
